### ISSUE TITLE
Histograms

### ISSUE THREAD

**Issue by eduardrusu** [eduardrusu/zMstarPDF#10]
In the python folder there are 5 histograms containing 16 weight ratios each. Each ratio is computed only for subfields that have more than 50% or 75% of their surface free of masks; the numbers on the histograms, for each of the W1-W4 subfields, are: peak of the histogram, average of the distribution, and median, respectively. For each weight ratio, I cut the distributions above a weight ratio of 10. This is mainly because when weighting by mass, mass^2 and mass^3, the tail of the distributions is very long and affects the statistics
    - histograms marked with "orig" do not consider P(z) or P(Mstar), just the best-fit values
    - those marked with "samp" consider a rudimentary P(z) and P(Mstar). I took the +/-68% confidence limits, and approximated the real distribution with a Gaussian of the appropriate sigma on each side. I then extracted 100 realizations of z and Mstar for each object (the final catalogue size is therefore 100 times the original)
    - those marked with "i23" contain only objects up to i=23, the rest up to i=24
    - the one marked with "noCFHTLENSsamp" consider the rudimentary P(z) and P(Mstar) only for the lens fields, but not for the calibration fields.
These are not the final histograms: for the lens fields, I used just a simple cut in class_star to separate stars and galaxies; also, for the calibration fields, I used z, Mstar, and their confidence levels from CFHTLens, therefore not computed in the same way with the lens fields

Conclusions at this stage (these may change when I recompute the histograms after fixing the issues above):
    - "samp" compared to "orig" have wider distributions, as expected, and also shifted, which is expected due to the asymmetrical error bars; the shifts seem very large
    - field W4 is no longer appears different from the others, as it did in the first histograms; might have been a bug 
    - 50% and 75% free surface fields are very similar
    - i<23 and i<24 limits: the comparison is not very useful now because the star-galaxy classification is not reliable; the distributions are much broader for i<23, and I'm not sure why
    - I worry that when we account for different systematics we will get large shifts between the average/median of the weight ratio distributions; the original idea is to use the size of the shifts as error bars for the average/median, but if these are too wide, they are not informative anymore
    - we need to decide what weights to use in order to get kappa_ext from the Millenium simulations; Do we use the weights Greene et al. suggested? do we use the ones with smallest scatter when accounting for different systematics?

**Comment by drphilmarshall** [comment]
Thanks for posting the images on [the wiki](https://github.com/eduardrusu/zMstarPDF/wiki)!
- Good question about how to decide which weights to use. I think we want to optimize our choices for _accuracy_, which means acceptably low bias and then maximum precision (smallest possible statistical uncertainty). So we'll know a lot more after probing the systematics - and maybe repeating our tests as best we can on the sims.
- With this working assumption that Pr(Mstar | z) = Pr(Mstar) (ie that z has been marginalised over), we are being maximally conservative: the joint Pr(Mstar,z) should give us more precision. I think this is the case for any weights that use Mstar, not just the ones that use both Mstar and z. It may not be a big concern when the photo-zs are good.

**Comment by eduardrusu** [comment]
Will close this issue, because the relevant discussion is in Rusu et al. 2017.
