### ISSUE TITLE
Check if CFHTLS deep is contained in CFHTLens and can replace Wide

### ISSUE THREAD

**Issue by eduardrusu** [eduardrusu/zMstarPDF#8]
This would solve the i=24 completeness issue

**Comment by eduardrusu** [comment]
Unfortunately it is not. Two of the deep fields do overlap with the wide, but it appears the data is not processed in the same way as the wide fields (e.g. seeing corrected).

**Comment by drphilmarshall** [comment]
Ah well - worth a look. Can you please double check the depth of the wide
fields though? I'm sure they are deeper than single visit LSST, which is
i=24... What depth/magnitude definition are you using? And what depthe
definition did we use in the Millennium comparison?

**Comment by eduardrusu** [comment]
Limiting magnitudes and completeness limits for CFHTLS are referenced below:
http://www4.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/megapipe/docs/photo.html
http://www.cfht.hawaii.edu/Science/CFHLS/T0007/T0007-docsu12.html
For extended sources, the 50% completeness is at i=24. CFHTLens does not provide estimates for extended sources, but their images should be deeper because they used average stacking, instead of median for CFHTLS.

**Comment by eduardrusu** [comment]
Also, even if we have access to the deep fields from CFHTLS, I prefer not to use them because of the differences with CFHTLens: the data has not been corrected for different seeing, the masks they use are totally different, the magnitude definitions that the catalogues quote are different.

**Comment by eduardrusu** [comment]
At the moment the only way I can think to test for systematics introduced by catalogue incompleteness is to recompute histograms for, say, i=23,23.5,24. This is also related to the galaxy/star classification issue for faint objects. Recomputing the histograms for different limiting mags should give us the systematics due to both of these issues
