### ISSUE TITLE
Contact CFHTLens authors

### ISSUE THREAD

**Issue by eduardrusu** [eduardrusu/zMstarPDF#9]
Need to email the authors of the CFHTLens papers on several issues:
    - Find out what value of h they used
    - See if we can get their BPZ and LePhare config files, and especially the interpolated templates they used
    - CFHTLens catalogue includes photometry and extinction values; but it's unclear to me if the photometry has already been corrected for extinction, or it needs to be
        - anything else?

**Comment by drphilmarshall** [comment]
Maybe ask how the Mstar values were obtained? Did they fix the redshift to
some value?

**Comment by eduardrusu** [comment]
Sent emails and received most of the files. I'm still missing some LePhare SEDs, hopefully I will have them soon.
The templates CFHTLens used for BPZ do not reach the IRAC bands,  I will have to extend them if I I want to include IRAC data in the photo-z calculation.

**Comment by drphilmarshall** [comment]
Hey @eduardrusu, any news from the CFHTLenS team? What's your proposed action plan?

**Comment by eduardrusu** [comment]
Hi @drphilmarshall!
Yes, as I was saying during the Telecon, I got what I needed from CFHTLenS. They sent me the exact configuration files and templates. I'm applying them to get the SED-based star-galaxy separation for the lens fields, as well as get z and Mstar using the same approach. I'm not comfortable with CFHTLenS classifying all i > 23 objects as galaxies, so what I plan to do is extend their joint size and color criteria to  23 < i < 24. For the CFHTLenS catalogue, I want to do this using the machine learning technique you mentioned. So as a check of systematics due to star-galaxy classification, I will plot the histograms as I did so far (all i > 23 objects as galaxies), but also by reclassifying the i>23 objects. 

I checked Stefan's simulations, and the painted galaxies are realistic (photoz codes recover the "specz"). I need to compute the weights for the simulated catalogue, in order to identify the LOSs with matching overdensities. The question is, do we use the z,Mstar from the simulated catalogue, or do we use codes to compute photoz and Mstar, like we do for CFHTLenS? The fact that we are only interested in ratios of weights could mean that this doesn't matter much. But if we do it as for CFHTLenS, and we are interested in the whole PDFs, we will need to use a supercomputer for both CFHTLenS and the simulations. Chris says he can probably get time on one.

**Comment by drphilmarshall** [comment]
Good idea to check that the MS galaxies yield accurate photo-zs. Perhaps
you can use this to argue that in the simulation fields, it's ok to compute
the comparison zeta ratios with the true redshifts and stellar masses. This
is certainly the cheapest procedure. We still need code that approximates,
and then samples from, the joint PDF P(zp,Mstar|data) given Le Phare
outputs.

The question is still, how much bias does this procedure introduce, and how
precise is it, in the derived P(kappa_ext)?

It's in this test that we will need to do more z-Mstar inference, I think.
We'd need to define a mock CFHTLS survey from the MS, and then infer zp and
Mstar for each galaxy in the same way that CFHTLenS did (which you can now
do). Then, you could make 100 mock HE0435s by selecting twin lens galaxies
from the simulation, and extracting mock catalogs that match the observed
one (in terms of magnitude limit, and spectroscopic coverage) - and then
measuring zp and Mstar in these as well. Then, you could derive a P(kappa)
for each mock system, and compare with the true ray-traced kappa in each
one. 100 lenses is probably enough to make a useful statement about bias
and precision.

Do you have a living document where you are keeping track of possible
sources of systematic error? Writing these down, as well as your plan of
action for testing Pr(kappa), is probably a good idea. You could use the
zMstarPDF wiki, and reserve the H0LiCOW wiki for telecon summaries, perhaps.

**Comment by eduardrusu** [comment]
Hi @drphilmarshall  @cdfassnacht !
I added a second page to the zMstarPDF wiki, outlining my work plan and the systematics checks I'm considering. Please let me know if you have any comments.

**Comment by drphilmarshall** [comment]
Cool, I'll go check it out. You can close this issue I think, and we'll
resume discussion on a new issue relating to The Plan.
